export let data = [{'description': 'Zorgt voor de stabiliteit en betrouwbaarheid van systemen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ontwikkelt en onderhoudt automatiseringstools.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Monitort systeemprestaties en reageert op incidenten.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Voert root cause analysis uit bij systeemstoringen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Beheert en optimaliseert de infrastructuur.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Implementeert en verbetert monitoring- en loggingoplossingen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Automatiseert herhalende taken en processen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ondersteunt en verbetert CI/CD-pijplijnen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Beheert cloud-infrastructuren zoals AWS, Azure, of Google Cloud.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Zorgt voor naleving van SLA\'s (Service Level Agreements).', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ontwikkelt en onderhoudt scripts voor systeembeheer.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Implementeert beveiligingsmaatregelen en best practices.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Voert systeemupgrades en patching uit.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ontwikkelt en test disaster recovery plannen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Optimaliseert serverconfiguraties voor prestaties.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Beheert en onderhoudt containerized applicaties met Docker en Kubernetes.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Werkt samen met ontwikkelaars om systeemvereisten te begrijpen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Implementeert infrastructuur als code (IaC) met tools zoals Terraform.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Analyseert systeem- en applicatielogs voor probleemoplossing.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Monitort netwerkprestaties en beveiliging.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Onderhoudt en beheert databaseclusters.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ontwikkelt en implementeert schaalbare oplossingen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Zorgt voor continue beschikbaarheid van diensten.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Voert stresstests en load tests uit.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Beheert versiebeheer en release management.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Documenteert processen en procedures.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Werkt aan capaciteitsplanning en resourcebeheer.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Zorgt voor proactieve probleemdetectie en -oplossing.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Beoordeelt en implementeert nieuwe technologieën en tools.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Blijft op de hoogte van de nieuwste ontwikkelingen op het gebied van systeembeheer en betrouwbaarheid.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ontwerpt en bouwt data-infrastructuur.', 'belongs_to': ['data engineer']},
{'description': 'Creëert en onderhoudt databases.', 'belongs_to': ['data engineer']},
{'description': 'Ontwikkelt ETL (Extract, Transform, Load) processen.', 'belongs_to': ['data engineer']},
{'description': 'Verwerkt en transformeert grote datasets.', 'belongs_to': ['data engineer']},
{'description': 'Automatiseert data-pijplijnen.', 'belongs_to': ['data engineer']},
{'description': 'Beheert en optimaliseert data-opslag.', 'belongs_to': ['data engineer']},
{'description': 'Integreert data uit verschillende bronnen.', 'belongs_to': ['data engineer']},
{'description': 'Zorgt voor de kwaliteit en integriteit van data.', 'belongs_to': ['data engineer']},
{'description': 'Implementeert data-architecturen.', 'belongs_to': ['data engineer']},
{'description': 'Schrijft en onderhoudt data scripts en queries.', 'belongs_to': ['data engineer']},
{'description': 'Ontwikkelt en implementeert datawarehouses.', 'belongs_to': ['data engineer']},
{'description': 'Beheert big data platforms zoals Hadoop en Spark.', 'belongs_to': ['data engineer']},
{'description': 'Implementeert en onderhoudt databeveiligingsmaatregelen.', 'belongs_to': ['data engineer']},
{'description': 'Optimaliseert data-opslagsystemen voor prestaties.', 'belongs_to': ['data engineer']},
{'description': 'Creëert en onderhoudt API’s voor data-access.', 'belongs_to': ['data engineer']},
{'description': 'Voert data cleaning en preprocessing uit.', 'belongs_to': ['data engineer']},
{'description': 'Bouwt schaalbare data-oplossingen.', 'belongs_to': ['data engineer']},
{'description': 'Monitort en onderhoudt data-pijplijnen.', 'belongs_to': ['data engineer']},
{'description': 'Ondersteunt data scientists en analisten.', 'belongs_to': ['data engineer']},
{'description': 'Ontwikkelt datamodellen en schema’s.', 'belongs_to': ['data engineer']},
{'description': 'Werkt met cloud data-opslag zoals AWS, Azure of Google Cloud.', 'belongs_to': ['data engineer']},
{'description': 'Voert data migraties uit.', 'belongs_to': ['data engineer']},
{'description': 'Monitort dataverkeersstromen en prestaties.', 'belongs_to': ['data engineer']},
{'description': 'Automatiseert dataverwerkingstaken.', 'belongs_to': ['data engineer']},
{'description': 'Maakt gebruik van SQL en NoSQL databases.', 'belongs_to': ['data engineer']},
{'description': 'Ontwikkelt real-time data-verwerkingssystemen.', 'belongs_to': ['data engineer']},
{'description': 'Beheert metadata en data catalogi.', 'belongs_to': ['data engineer']},
{'description': 'Werkt samen met software-ontwikkelaars voor data-integratie.', 'belongs_to': ['data engineer']},
{'description': 'Voert data-backups en herstelprocedures uit.', 'belongs_to': ['data engineer']},
{'description': 'Blijft op de hoogte van de nieuwste data-engineering technologieën en best practices.', 'belongs_to': ['data engineer']},
{'description': 'Verzamelt en organiseert grote datasets.', 'belongs_to': ['data scientist']},
{'description': 'Voert geavanceerde statistische analyses uit.', 'belongs_to': ['data scientist']},
{'description': 'Ontwikkelt machine learning-modellen.', 'belongs_to': ['data scientist']},
{'description': 'Interpreteert complexe data voor bedrijfsinzichten.', 'belongs_to': ['data scientist']},
{'description': 'Voert data cleaning en preprocessing uit.', 'belongs_to': ['data scientist']},
{'description': 'Visualiseert data om inzichten te delen.', 'belongs_to': ['data scientist']},
{'description': 'Ontdekt trends en patronen in data.', 'belongs_to': ['data scientist']},
{'description': 'Stelt voorspellende modellen op.', 'belongs_to': ['data scientist']},
{'description': 'Werkt samen met stakeholders om data-behoeften te begrijpen.', 'belongs_to': ['data scientist']},
{'description': 'Analyseert klantgedrag en markttrends.', 'belongs_to': ['data scientist']},
{'description': 'Maakt gebruik van programmeertalen zoals Python en R.', 'belongs_to': ['data scientist']},
{'description': 'Ontwikkelt algoritmes voor dataverwerking.', 'belongs_to': ['data scientist']},
{'description': 'Optimaliseert bedrijfsprocessen door data-analyse.', 'belongs_to': ['data scientist']},
{'description': 'Creëert rapporten en dashboards voor dataweergave.', 'belongs_to': ['data scientist']},
{'description': 'Ontwikkelt A/B-testen voor productverbetering.', 'belongs_to': ['data scientist']},
{'description': 'Identificeert KPI\'s (Key Performance Indicators).', 'belongs_to': ['data scientist']},
{'description': 'Gebruikt big data-technologieën zoals Hadoop en Spark.', 'belongs_to': ['data scientist']},
{'description': 'Voert tekst- en spraakanalyse uit.', 'belongs_to': ['data scientist']},
{'description': 'Integreert data uit verschillende bronnen.', 'belongs_to': ['data scientist']},
{'description': 'Bouwt en implementeert data warehouses.', 'belongs_to': ['data scientist']},
{'description': 'Analyseert financiële gegevens voor risico en rendement.', 'belongs_to': ['data scientist']},
{'description': 'Ontwikkelt data-driven strategieën.', 'belongs_to': ['data scientist']},
{'description': 'Test en valideert modellen om nauwkeurigheid te waarborgen.', 'belongs_to': ['data scientist']},
{'description': 'Voert netwerk- en grafenanalyse uit.', 'belongs_to': ['data scientist']},
{'description': 'Ontwikkelt aanbevelingssystemen.', 'belongs_to': ['data scientist']},
{'description': 'Analyseert webverkeer en gebruikersinteracties.', 'belongs_to': ['data scientist']},
{'description': 'Past deep learning-technieken toe op beeld- en spraakanalyse.', 'belongs_to': ['data scientist']},
{'description': 'Werkt aan tijdreeksanalyse en voorspellende modellering.', 'belongs_to': ['data scientist']},
{'description': 'Beoordeelt en selecteert relevante datafuncties.', 'belongs_to': ['data scientist']},
{'description': 'Blijft op de hoogte van de nieuwste datawetenschapstechnieken en -tools.', 'belongs_to': ['data scientist']},
{'description': 'Ontwerpt grafieken om gegevens te illustreren.', 'belongs_to': ['datavisualisator']},
{'description': 'Creëert interactieve dashboards voor datamonitoring.', 'belongs_to': ['datavisualisator']},
{'description': 'Verwerkt ruwe data tot visuele formats.', 'belongs_to': ['datavisualisator']},
{'description': 'Analyseert datasets voor visuele presentatie.', 'belongs_to': ['datavisualisator']},
{'description': 'Maakt complexe data toegankelijk voor leken.', 'belongs_to': ['datavisualisator']},
{'description': 'Visualiseert trends en patronen in data.', 'belongs_to': ['datavisualisator']},
{'description': 'Verbetert dataverhaal met visuele elementen.', 'belongs_to': ['datavisualisator']},
{'description': 'Gebruikt softwaretools voor datavisualisatie.', 'belongs_to': ['datavisualisator']},
{'description': 'Ontwikkelt visuele data-rapporten voor stakeholders.', 'belongs_to': ['datavisualisator']},
{'description': 'Voert data-analyse uit om inzichten te onthullen.', 'belongs_to': ['datavisualisator']},
{'description': 'Gebruikt kleuren en vormen om data te representeren.', 'belongs_to': ['datavisualisator']},
{'description': 'Converteert statistieken naar visuele grafieken.', 'belongs_to': ['datavisualisator']},
{'description': 'Creëert infographics voor dataweergave.', 'belongs_to': ['datavisualisator']},
{'description': 'Ontwerpt visuele hulpmiddelen voor beslissingsondersteuning.', 'belongs_to': ['datavisualisator']},
{'description': 'Past datavisualisatieprincipes toe om duidelijkheid te verbeteren.', 'belongs_to': ['datavisualisator']},
{'description': 'Transformeert cijfers in begrijpelijke beelden.', 'belongs_to': ['datavisualisator']},
{'description': 'Ontwikkelt visualisaties voor gegevensverkenning.', 'belongs_to': ['datavisualisator']},
{'description': 'Presentatie van data via diagrammen en grafieken.', 'belongs_to': ['datavisualisator']},
{'description': 'Verzamelt en analyseert gegevens voor visualisatie.', 'belongs_to': ['datavisualisator']},
{'description': 'Integreert datavisualisaties in presentaties.', 'belongs_to': ['datavisualisator']},
{'description': 'Verbetert dataverstaanbaarheid door visualisatie.', 'belongs_to': ['datavisualisator']},
{'description': 'Ontwerpt gebruikersvriendelijke datavisualisatie-interfaces.', 'belongs_to': ['datavisualisator']},
{'description': 'Brengt datasets samen voor visuele analyse.', 'belongs_to': ['datavisualisator']},
{'description': 'Creëert visuele representaties van data-analyses.', 'belongs_to': ['datavisualisator']},
{'description': 'Maakt gebruik van verschillende grafiektypen voor datavisualisatie.', 'belongs_to': ['datavisualisator']},
{'description': 'Bouwt visuele data dashboards voor real-time monitoring.', 'belongs_to': ['datavisualisator']},
{'description': 'Ontwikkelt visuele data-inzichten voor bedrijfsstrategieën.', 'belongs_to': ['datavisualisator']},
{'description': 'Verzorgt visuele verslaglegging van onderzoeksresultaten.', 'belongs_to': ['datavisualisator']},
{'description': 'Identificeert kerninzichten door visuele data-analyse.', 'belongs_to': ['datavisualisator']},
{'description': 'Creëert gepersonaliseerde visualisaties voor specifieke doeleinden.', 'belongs_to': ['datavisualisator']}

];