export let data = [{'description': 'Ik zorg voor de stabiliteit en betrouwbaarheid van systemen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik ontwikkel en onderhoud automatiseringstools.', 'belongs_to': ['Data Engineer', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik monitor systeemprestaties en reageert op incidenten.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik voer root cause analysis uit bij systeemstoringen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik beheer de infrastructuur.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik optimaliseerd de infrastructuur.', 'belongs_to': ['Data Engineer', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik implementeer en verbeter monitoring- en loggingoplossingen.', 'belongs_to': ['Data Engineer', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik ondersteun en verbetert CI/CD-pijplijnen.', 'belongs_to': ['Data Engineer', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik zorg voor naleving van SLA\'s (Service Level Agreements).', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik ontwikkel en onderhoud scripts voor systeembeheer.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik implementeer beveiligingsmaatregelen en best practices.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik voer systeemupgrades en patching uit.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik ontwikkel en test disaster recovery plannen.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik optimaliseer het gebruik binnen de server.', 'belongs_to': ['Data Engineer', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik beheer en onderhoud containerized applicaties met Docker en Kubernetes.', 'belongs_to': ['Data Engineer', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik analyseer systeem- en applicatielogs voor probleemoplossing.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik ontwikkel en implementeer schaalbare infrastructuur.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik zorg voor continue beschikbaarheid van diensten.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik voer stresstests en load tests uit.', 'belongs_to': ['Data Engineer', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik documenteer processen en procedures.', 'belongs_to': ['Data Engineer', 'Data Scientist', 'Datavisualisator', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik werk aan capaciteitsplanning en resourcebeheer.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik zorg voor proactieve probleemdetectie en -oplossing.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik blijf op de hoogte van de nieuwste ontwikkelingen op het gebied van systeembeheer en betrouwbaarheid.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik ontwerp en bouwt data-infrastructuur.', 'belongs_to': ['Data Engineer', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik creëer en onderhoud databases.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik ontwikkel ETL (Extract, Transform, Load) processen.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik verwerk en transformeer grote datasets.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik beheer en optimaliseer data-opslag.', 'belongs_to': ['Data Engineer', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik integreer data uit verschillende bronnen.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik zorg voor de kwaliteit en integriteit van data.', 'belongs_to': ['Data Engineer', 'Data Scientist']},
{'description': 'Ik implementeer data-architecturen.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik schrijf en onderhoudt data scripts en queries.', 'belongs_to': ['Data Engineer', 'Data Scientist']},
{'description': 'Ik creëer en onderhoudt API’s voor data-access.', 'belongs_to': ['Data Engineer', 'Data Scientist']},
{'description': 'Ik voer data cleaning en preprocessing uit.', 'belongs_to': ['Data Engineer', 'Data Scientist', 'Datavisualisator']},
{'description': 'Ik bouw schaalbare data-oplossingen.', 'belongs_to': ['Data Engineer', 'Data Scientist', 'Datavisualisator']},
{'description': 'Ik monitor en onderhoudt data-pijplijnen.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik ondersteun Data Scientists en Datavisualisatoren.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik ontwikkel datamodellen en schema’s.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik voer data migraties uit.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik monitor dataverkeersstromen en prestaties.', 'belongs_to': ['Data Engineer', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik maak gebruik van databases.', 'belongs_to': ['Data Engineer', 'Data Scientist', 'Datavisualisator', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik ontwikkel real-time data-verwerkingssystemen.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik voer data-backups en herstelprocedures uit.', 'belongs_to': ['Site Reliability Engineer (SRE)']},
{'description': 'Ik blijf op de hoogte van de nieuwste data-engineering technologieën en best practices.', 'belongs_to': ['Data Engineer']},
{'description': 'Ik voer geavanceerde statistische analyses uit.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik ontwikkel machine learning-modellen.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik interpreteer complexe data voor inzichten.', 'belongs_to': ['Data Scientist', 'Datavisualisator']},
{'description': 'Ik visualiseer data om inzichten te delen.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik ontdek trends en patronen in data.', 'belongs_to': ['Data Scientist', 'Datavisualisator']},
{'description': 'Ik stel voorspellende modellen op.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik werk samen met stakeholders om data-behoeften te begrijpen.', 'belongs_to': ['Data Engineer', 'Data Scientist', 'Datavisualisator', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik werk voornamelijk met Python.', 'belongs_to': ['Data Engineer', 'Data Scientist']},
{'description': 'Ik werk voornamelijk met JavaScript en C#.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik voer tekstanalyse uit.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik integreer data uit verschillende bronnen.', 'belongs_to': ['Data Engineer', 'Data Scientist', 'Datavisualisator']},
{'description': 'Ik test en valideer modellen om nauwkeurigheid te waarborgen.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik identificeer objecten op satelliet beelden via algoritmes.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik pas deep learning-technieken toe op beelden.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik werk aan tijdreeksanalyse en voorspellende modellering.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik beoordeel en selecteer relevante datafuncties.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik blijf op de hoogte van de nieuwste AI-technieken en -tools.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik ontwerp grafieken om gegevens te illustreren.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik verwerk ruwe data tot visuele formats.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik analyseer datasets voor visuele presentatie.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik maak complexe data toegankelijk voor leken door deze te visualiseren.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik visualiseer trends en patronen in data.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik verbeter dataverhaal met beeldende elementen.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik gebruik kleuren en vormen om data te representeren.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik ontwerp visuele hulpmiddelen voor beslissingsondersteuning.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik pas psychologische principes toe om duidelijkheid te verbeteren.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik ontwikkel visuele oplossingen voor data exploratie door derden.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik verbeter toegankelijkheid en datageletterdheid door visualisatie.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik ontwerp gebruikersvriendelijke user interfaces.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik kies de optimale grafiektypen.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik creëer maatwerk visualisaties voor specifieke doeleinden.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik verken nieuwe visualisatiemogelijkheden voor de organisatie.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik verken nieuwe AI toepassingen voor de organisatie.', 'belongs_to': ['Data Scientist']},
{'description': 'Ik heb als doel om de organisatie meer datagedreven te laten werken.', 'belongs_to': ['Data Engineer', 'Data Scientist', 'Datavisualisator', 'Site Reliability Engineer (SRE)']},
{'description': 'Ik maak data immersief middels het toepassen van XR (AR en VR).', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik maak databelevingen.', 'belongs_to': ['Datavisualisator']},
{'description': 'Ik werk aan AI-modellen voor datagedreven asset management.', 'belongs_to': ['Data Engineer', 'Data Scientist']},
{'description': 'Ik maak visualisaties voor op de computer, telefoon of de AR/VR-bril.', 'belongs_to': ['Data Engineer', 'Datavisualisator']}];